basePath: /
consumes:
- application/json
definitions:
  CreateDeliveryRequest:
    properties:
      delivery_address:
        type: string
        x-go-name: DeliveryAdd
      delivery_email:
        type: string
        x-go-name: DeliveryEmail
      delivery_latitude:
        type: string
        x-go-name: DeliveryLat
      delivery_longitude:
        type: string
        x-go-name: DeliveryLong
      delivery_name:
        type: string
        x-go-name: DeliveryName
      delivery_phone:
        type: string
        x-go-name: DeliveryPhone
      descriptioin:
        type: string
        x-go-name: Description
      pickup_address:
        type: string
        x-go-name: PickupAdd
      pickup_email:
        type: string
        x-go-name: PickupEmail
      pickup_latitue:
        type: string
        x-go-name: PickupLat
      pickup_longitude:
        type: string
        x-go-name: PickupLong
      pickup_name:
        type: string
        x-go-name: PickupName
      pickup_phone:
        type: string
        x-go-name: PickupPhone
    type: object
    x-go-package: github.com/farouqu/delivery-api/delivery
  DeliveryEstimateRequest:
    properties:
      delivery_latitude:
        type: string
        x-go-name: DeliveryLat
      delivery_longitude:
        type: string
        x-go-name: DeliveryLong
      pickup_latitude:
        type: string
        x-go-name: PickupLat
      pickup_longitude:
        type: string
        x-go-name: PickupLong
    type: object
    x-go-package: github.com/farouqu/delivery-api/delivery
  DeliveryResponse:
    properties:
      distance:
        format: int64
        type: integer
        x-go-name: Distance
      fare:
        format: int64
        type: integer
        x-go-name: Fare
      order_id:
        type: string
        x-go-name: OrderID
      time:
        format: int64
        type: integer
        x-go-name: Time
    type: object
    x-go-package: github.com/farouqu/delivery-api/delivery
  EstimateResponse:
    properties:
      distance:
        format: int64
        type: integer
        x-go-name: Distance
      fare:
        format: int64
        type: integer
        x-go-name: Fare
      time:
        format: int64
        type: integer
        x-go-name: Time
    type: object
    x-go-package: github.com/farouqu/delivery-api/delivery
host: localhost
info:
  description: Documentation of our Delivery API.
  title: Delivery.
  version: 1.0.0
paths:
  /delivery_estimate:
    post:
      operationId: idDelivery
      parameters:
      - description: Fetches the estimate for a delivery order.
        in: body
        name: Body
        schema:
          $ref: '#/definitions/DeliveryEstimateRequest'
      responses:
        "200":
          $ref: '#/responses/estimateSuccessResponse'
      summary: Fetches the estimate for a delivery order.
      tags:
      - delivery_estimate
  /delivery_order:
    post:
      description: Creates a delivery order
      operationId: idOrder
      parameters:
      - description: Creates a delivery order and returns the information
        in: body
        name: Body
        schema:
          $ref: '#/definitions/CreateDeliveryRequest'
      responses:
        "200":
          $ref: '#/responses/deliverySuccessResponse'
      tags:
      - delivery_order
produces:
- application/json
responses:
  deliverySuccessResponse:
    description: Successful delivery order
    schema:
      $ref: '#/definitions/DeliveryResponse'
  estimateSuccessResponse:
    description: Successful estimate created response.
    schema:
      $ref: '#/definitions/EstimateResponse'
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
